name: document spellcheck workflow
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: spellcheck checkout
       uses: actions/checkout@v2
     - name: download dictionary
       run: |
        wget https://raw.githubusercontent.com/sujith-mn/.github/master/en-devonfw.dict -O ./en-devonfw.dict
     - uses: igsekor/pyspelling-any@v0.0.2
       name: Spellcheck
